spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: ots
    password: ots
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
server:
  context-path: /ots
mybatis:
  config-location: classpath:mybatis.xml
logging:
#  file: log4j.properties
  level:
    org.springframework.web: DEBUG
    org.apache.ibatis: DEBUG
    java.sql.Connection: DEBUG
    java.sql.Statement: DEBUG
    java.sql.PreparedStatement: DEBUG
    java.sql.ResultSet: DEBUG